export const CONTACT_CREATE_REQUEST = "CONTACT_CREATE_REQUEST";
export const CONTACT_CREATE_SUCCESS = "CONTACT_CREATE_SUCCESS";
export const CONTACT_CREATE_FAIL = "CONTACT_CREATE_FAIL";

export const CONTACT_LIST_REQUEST = "CONTACT_LIST_REQUEST";
export const CONTACT_LIST_SUCCESS = "CONTACT_LIST_SUCCESS";
export const CONTACT_LIST_FAIL = "CONTACT_LIST_FAIL";

export const CONTACT_DELETE_REQUEST = "CONTACT_DELETE_REQUEST";
export const CONTACT_DELETE_SUCCESS = "CONTACT_DELETE_SUCCESS";
export const CONTACT_DELETE_FAIL = "CONTACT_DELETE_FAIL";

export const CONTACT_EDIT_REQUEST = "CONTACT_EDIT_REQUEST";
export const CONTACT_EDIT_SUCCESS = "CONTACT_EDIT_SUCCESS";
export const CONTACT_EDIT_FAIL = "CONTACT_EDIT_FAIL";
export const CONTACT_EDIT_RESET = "CONTACT_EDIT_RESET";

export const CONTACT_GETBYID_REQUEST = "CONTACT_GETBYID_REQUEST";
export const CONTACT_GETBYID_SUCCESS = "CONTACT_GETBYID_SUCCESS";
export const CONTACT_GETBYID_FAIL = "CONTACT_GETBYID_FAIL";
